---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9
dependencies:
  ansible_core:
    package_pip: ansible-core>=2.15.8
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt
additional_build_steps:
  append_base:
    - RUN yum upgrade -y
    - RUN yum install -y python3
    - RUN yum install -y python3-pip
    - RUN yum install -y krb5-devel
    - RUN yum install -y krb5-libs
    - RUN yum install -y krb5-workstation
    - RUN yum install -y python3-devel
    - RUN yum install -y gcc
    - RUN yum install -y openssh-clients
    - RUN yum install -y epel-release
    - RUN python3 -m pip install --upgrade --force pip
    - RUN pip3 install pypsrp[kerberos]
    - RUN pip3 install pyVim PyVmomi
    - COPY --from=quay.io/project-receptor/receptor:latest /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
